In [1]:
import cv2
import numpy as np
from affine import Affine

In [11]:
# real_objPose & real_armPose

# Point-2 (top-right)
# - Translation: [0.160, -0.666, 0.010]: real_objPose
# - Translation: [0.091, -0.629, 0.015]: real_armPose
# - Rotation: in Quaternion [0.555, 0.828, 0.077, -0.017]
#             in RPY (radian) [3.031, -0.114, 1.967]
#             in RPY (degree) [173.687, -6.541, 112.712]

# Point-3 (bottom-right)
# - Translation: [-0.148, -0.633, -0.001]
# - Translation: [-0.110, -0.626, -0.012]
# - Rotation: in Quaternion [0.640, 0.763, 0.081, -0.049]
#             in RPY (radian) [3.080, -0.179, 1.752]
#             in RPY (degree) [176.485, -10.250, 100.354]
            
# Point-4 (bottom-left)
# - Translation: [-0.147, -0.443, 0.010]
# - Translation: [-0.134, -0.523, -0.000]

# --------------------------------------------------------------------------------

# GraspPose Point
# - Translation: [-0.091, -0.958, 0.022]
# - Translation: [-0.023, -0.671, 0.006]
# - Rotation: in Quaternion [0.016, 0.998, 0.060, -0.031]
#             in RPY (radian) [3.023, -0.065, 3.113]
#             in RPY (degree) [173.204, -3.709, 178.335]

In [13]:
# # 3 points: p2,p3,p4

# pts_obj = np.float32([[0.160, -0.666],[-0.148, -0.633],[-0.147, -0.443]])
# pts_arm = np.float32([[0.091, -0.629],[-0.110, -0.626],[-0.134, -0.523]])

# M_obj = cv2.getAffineTransform(pts_obj,pts_arm); print('Matrix:\n', M_obj)

# # real_data from experiment:
# obj_65 = np.array([[0.160, -0.666, 0.001], [-0.091, -0.958, 0.022]])
# obj_65 = obj_65[0].reshape(3,1)
# cali_armPose = np.dot(M_obj, obj_65)
# cali_armPose

In [36]:
pts_obj = np.float32([[0.160, -0.666], 
                      [-0.148, -0.633],
                      [-0.147, -0.443]])

pts_arm = np.float32([[0.091, -0.629],
                      [-0.110, -0.626],
                      [-0.134, -0.523]])

M = cv2.getAffineTransform(pts_obj, pts_arm); print('Matrix:', M)
# real_data from experiment:
obj_65 = np.array([[0.160, -0.666,1],[-0.091, -0.958, 1]])
# obj_65 = np.array([[0.160, -0.666, 0.001], [-0.091, -0.958, 0.022]])
obj_65 = obj_65[1].reshape(3,1); print(obj_65)
real_arm_pose = np.dot(M, obj_65)
real_arm_pose

Matrix: [[ 0.63870339 -0.1296774  -0.09755769]
 [ 0.0483151   0.54185082 -0.27585778]]
[[-0.091]
 [-0.958]
 [ 1.   ]]


array([[-0.03144875],
       [-0.79934753]])

In [33]:
# 3 points: p2,p3,p4

pts_obj = np.float32([[0.160, -0.666],
                      [-0.148, -0.633],
                      [-0.147, -0.443]])
pts_arm = np.float32([[0.091, -0.629],
                      [-0.110, -0.626],
                      [-0.134, -0.523]])

M_obj = cv2.getAffineTransform(pts_obj,pts_arm); print('Matrix:', M_obj)

# real_data from experiment:
obj_65 = np.array([[0.160, -0.666, 1], [-0.091, -0.958, 0.022]])
obj_65 = obj_65[0].reshape(3,1); print(obj_65)
cali_armPose = np.dot(M_obj, obj_65)
cali_armPose

Matrix: [[ 0.63870339 -0.1296774  -0.09755769]
 [ 0.0483151   0.54185082 -0.27585778]]
[[ 0.16 ]
 [-0.666]
 [ 1.   ]]


array([[ 0.091],
       [-0.629]])

In [ ]:
# using mapping method, but not precise.

In [42]:
from scipy.interpolate import interp1d

In [43]:
map_x = interp1d( [0.160,-0.148], [0.091,-0.110] ) # x = -0.098 = -0.028 -> needing to tune x each time.
map_y = interp1d( [-0.666,-0.633] , [-0.629,-0.523] )  

In [51]:
obj_65 = np.array([-0.091, -0.958])
xx = np.float(map_x(obj_65[0])); print('xx=', xx)
# yy = np.float(map_y(obj_65[1])); print('yy=', yy)

xx= -0.07280194805194806


In [ ]:
# GraspPose Point
# - Translation: [-0.091, -0.958, 0.022]
# - Translation: [-0.023, -0.671, 0.006]